spring.application.name=aiapi

server.port=${PORT:8080}

spring.config.import=optional:classpath:secret.properties

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/win_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ai.api.key=${AI_API_KEY:}
jwt.secret=${JWT_SECRET:myLocalSecretKey123456789012345678901234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true